export const SOVEREIGN_CONFIGS: Record<string, { name: string; flag: string; color: string; capital: string; desc: string }> = {
  // Asia
  AFG: { name: "أفغانستان", flag: "🇦🇫", color: "#1e293b", capital: "كابول", desc: "دولة جبلية ذات تضاريس وعرة وثروات كامنة." },
  UZB: { name: "أوزبكستان", flag: "🇺🇿", color: "#3b82f6", capital: "طشقند", desc: "قلب طريق الحرير ودولة حبيسة استراتيجية." },
  ARM: { name: "أرمينيا", flag: "🇦🇲", color: "#f59e0b", capital: "يريفان", desc: "دولة تاريخية عريقة في القوقاز." },
  AZE: { name: "أذربيجان", flag: "🇦🇿", color: "#0ea5e9", capital: "باكو", desc: "عملاق النفط والغاز في بحر قزوين." },
  ARE: { name: "الإمارات", flag: "🇦🇪", color: "#10b981", capital: "أبوظبي", desc: "مركز عالمي للتجارة والتكنولوجيا ورأس المال." },
  IDN: { name: "إندونيسيا", flag: "🇮🇩", color: "#ef4444", capital: "جاكرتا", desc: "أكبر أرخبيل في العالم بكثافة سكانية هائلة." },
  IRN: { name: "إيران", flag: "🇮🇷", color: "#22c55e", capital: "طهران", desc: "قوة إقليمية ذات تاريخ إمبراطوري ونفوذ شاسع." },
  PAK: { name: "باكستان", flag: "🇵🇰", color: "#16a34a", capital: "إسلام آباد", desc: "قوة نووية إسلامية ذات تعداد سكاني جبار." },
  BHR: { name: "البحرين", flag: "🇧🇭", color: "#dc2626", capital: "المنامة", desc: "مركز مالي بارز في الخليج العربي." },
  BRN: { name: "بروناي", flag: "🇧🇳", color: "#eab308", capital: "بندر سري بكاوان", desc: "دولة غنية بالنفط على جزيرة بورنيو." },
  BGD: { name: "بنغلاديش", flag: "🇧🇩", color: "#15803d", capital: "دكا", desc: "كثافة سكانية عالية وأراض خصبة متدفقة." },
  BTN: { name: "بوتان", flag: "🇧🇹", color: "#fb923c", capital: "تيمفو", desc: "مملكة سلسلة جبال الهيمالايا المعزولة." },
  THA: { name: "تايلاند", flag: "🇹🇭", color: "#3b82f6", capital: "بانكوك", desc: "قوة سياحية واقتصادية هائلة في جنوب شرق آسيا." },
  TKM: { name: "تركمانستان", flag: "🇹🇲", color: "#22c55e", capital: "عشق آباد", desc: "دولة صحراوية غنية بمصادر الغاز الطبيعي الهائلة." },
  TUR: { name: "تركيا", flag: "🇹🇷", color: "#ef4444", capital: "أنقرة", desc: "قوة أوراسية استراتيجية تربط الشرق بالغرب." },
  TLS: { name: "تيمور الشرقية", flag: "🇹🇱", color: "#dc2626", capital: "ديلي", desc: "دولة فتية تطل على المحيط الهادئ." },
  LKA: { name: "سريلانكا", flag: "🇱🇰", color: "#b91c1c", capital: "كولمبو", desc: "جزيرة استراتيجية غنية بالموارد الطبيعية." },
  SAU: { name: "السعودية", flag: "🇸🇦", color: "#10b981", capital: "الرياض", desc: "زعيمة قطاع الطاقة العالمي ومحور استراتيجي إسلامي." },
  SGP: { name: "سنغافورة", flag: "🇸🇬", color: "#ef4444", capital: "سنغافورة", desc: "مركز اقتصادي وتجاري عالمي شديد التقدم." },
  SYR: { name: "سوريا", flag: "🇸🇾", color: "#b91c1c", capital: "دمشق", desc: "قلب المشرق وعمق تاريخي واستراتيجي بامتياز." },
  TJK: { name: "طاجيكستان", flag: "🇹🇯", color: "#ef4444", capital: "دوشنبه", desc: "تتمتع بجبال الشاهقة وموارد هائلة للمياه." },
  OMN: { name: "عمان", flag: "🇴🇲", color: "#16a34a", capital: "مسقط", desc: "إمبراطورية تاريخية وإرث بحري طويل." },
  IRQ: { name: "العراق", flag: "🇮🇶", color: "#dc2626", capital: "بغداد", desc: "بلاد الرافدين والمهد الحضاري وصاحبة الاحتياطيات الهائلة." },
  PSE: { name: "فلسطين", flag: "🇵🇸", color: "#16a34a", capital: "القدس", desc: "أرض مقدسة ذات وزن رمزي وهام إقليميا." },
  PHL: { name: "الفلبين", flag: "🇵🇭", color: "#2563eb", capital: "مانيلا", desc: "أرخبيل كبير يعج بالنشاط والحركة الاستراتيجية." },
  VNM: { name: "فيتنام", flag: "🇻🇳", color: "#dc2626", capital: "هانوي", desc: "قوة إقليمية صاعدة ذات سجل عسكري مهيب." },
  QAT: { name: "قطر", flag: "🇶🇦", color: "#7c2d12", capital: "الدوحة", desc: "عملاق تصدير الغاز الطبيعي المسال والنفوذ القوي." },
  KGZ: { name: "قيرغيزستان", flag: "🇰🇬", color: "#dc2626", capital: "بيشكيك", desc: "دولة جبلية تمتلك مقومات طبيعية بأسيا الوسطى." },
  CYP: { name: "قبرص", flag: "🇨🇾", color: "#f59e0b", capital: "نيقوسيا", desc: "جزيرة متوسطية بوزن أوراسي استراتيجي." },
  KAZ: { name: "كازاخستان", flag: "🇰🇿", color: "#0ea5e9", capital: "أستانا", desc: "أكبر دولة حبيسة بالعالم بموارد يورانيوم ضخمة." },
  KHM: { name: "كمبوديا", flag: "🇰🇭", color: "#1e3a8a", capital: "بنوم بنه", desc: "حاضنة حضارات عريقة في الهند الصينية." },
  KOR: { name: "كوريا الجنوبية", flag: "🇰🇷", color: "#3b82f6", capital: "سيول", desc: "عملاق التكنولوجيا المتطورة والاقتصاد الشرس." },
  PRK: { name: "كوريا الشمالية", flag: "🇰🇵", color: "#dc2626", capital: "بيونغيانغ", desc: "قوة نووية منعزلة ذات أيديولوجية حربية." },
  KWT: { name: "الكويت", flag: "🇰🇼", color: "#22c55e", capital: "الكويت", desc: "إمارة غنية باحتياطيات نفطية وموقع استراتيجي." },
  LBN: { name: "لبنان", flag: "🇱🇧", color: "#ef4444", capital: "بيروت", desc: "همزة الوصل البحرية والتاريخية." },
  LAO: { name: "لاوس", flag: "🇱🇦", color: "#dc2626", capital: "فيينتيان", desc: "دولة حبيسة غنية بالطاقة المائية الكارستية." },
  MYS: { name: "ماليزيا", flag: "🇲🇾", color: "#2563eb", capital: "كوالالمبور", desc: "نمر آسيوي بوزن اقتصادي صناعي." },
  MDV: { name: "المالديف", flag: "🇲🇻", color: "#16a34a", capital: "ماليه", desc: "أرخبيل استوائي خلاب بالمحيط الهندي." },
  EGY: { name: "مصر", flag: "🇪🇬", color: "#f43f5e", capital: "القاهرة", desc: "قوة تاريخية مسيطرة على الممرات المائية وبوابات القارات." },
  MNG: { name: "منغوليا", flag: "🇲🇳", color: "#ea580c", capital: "أولان باتور", desc: "موطن الإمبراطورية الأكبر مساحة والتضاريس القاسية." },
  MMR: { name: "ميانمار", flag: "🇲🇲", color: "#eab308", capital: "نايبيداو", desc: "موطن الثروات الاستوائية والحكم العسكري الصارم." },
  IND: { name: "الهند", flag: "🇮🇳", color: "#f97316", capital: "نيودلهي", desc: "قوة نووية عملاقة وكثافة بشرية وتزايد تقني." },
  HKG: { name: "هونغ كونغ", flag: "🇭🇰", color: "#dc2626", capital: "هونغ كونغ", desc: "مركز مالي واستثماري عالمي فائق." },
  JPN: { name: "اليابان", flag: "🇯🇵", color: "#ef4444", capital: "طوكيو", desc: "القوة التكنولوجية العظمى في المحيط الهادي." },
  YEM: { name: "اليمن", flag: "🇾🇪", color: "#dc2626", capital: "صنعاء", desc: "الحارس الجبلي لمضيق باب المندب." },
  JOR: { name: "الأردن", flag: "🇯🇴", color: "#1e293b", capital: "عمان", desc: "حجر الزاوية الجيوسياسي لبلاد الشام." },
  CHN: { name: "الصين", flag: "🇨🇳", color: "#f97316", capital: "بكين", desc: "الوريثة الصناعية وصاحبة أضخم جيش بشري." },

  // Africa
  ETH: { name: "إثيوبيا", flag: "🇪🇹", color: "#16a34a", capital: "أديس أبابا", desc: "القوة الجبلية ومقر الاتحاد الأفريقي." },
  ERI: { name: "إريتريا", flag: "🇪🇷", color: "#0ea5e9", capital: "أسمرة", desc: "دولة عسكرية تطل على أهم ممرات البحر الأحمر." },
  AGO: { name: "أنغولا", flag: "🇦🇴", color: "#dc2626", capital: "لواندا", desc: "دولة حيوية منتجة للنفط والماس." },
  UGA: { name: "أوغندا", flag: "🇺🇬", color: "#1e293b", capital: "كمبالا", desc: "لؤلؤة أفريقيا ذات موارد مائية ضخمة." },
  CAF: { name: "أفريقيا الوسطى", flag: "🇨🇫", color: "#3b82f6", capital: "بانغي", desc: "قلب القارة ذو التضاريس الطبيعية الشاسعة." },
  BEN: { name: "بنين", flag: "🇧🇯", color: "#22c55e", capital: "بورتو نوفو", desc: "منطقة عبور استراتيجية لغرب أفريقيا." },
  BWA: { name: "بوتسوانا", flag: "🇧🇼", color: "#0ea5e9", capital: "غابورون", desc: "معقل مناجم الألماس ومحميات السفاري." },
  BFA: { name: "بوركينا فاسو", flag: "🇧🇫", color: "#16a34a", capital: "واغادوغو", desc: "بلد الرجال النزهاء والاستثمارات المعدنية." },
  BDI: { name: "بوروندي", flag: "🇧🇮", color: "#ef4444", capital: "غيتيغا", desc: "دولة كثيفة السكان في قلب القارة." },
  TCD: { name: "تشاد", flag: "🇹🇩", color: "#2563eb", capital: "نجامينا", desc: "عمق القارة الصحراوي الجيوسياسي." },
  TZA: { name: "تنزانيا", flag: "🇹🇿", color: "#16a34a", capital: "دودوما", desc: "واجهة الساحل الشرقي ومركز نمو اقتصادي." },
  TUN: { name: "تونس", flag: "🇹🇳", color: "#dc2626", capital: "تونس", desc: "بوابة البحر المتوسط الشمالية لأفريقيا." },
  TGO: { name: "توغو", flag: "🇹🇬", color: "#16a34a", capital: "لومي", desc: "ملتقى تجاري استراتيجي لشرق خليج غينيا." },
  DZA: { name: "الجزائر", flag: "🇩🇿", color: "#16a34a", capital: "الجزائر", desc: "أكبر مساحة سيادية وقوة بترولية كبرى." },
  ZAF: { name: "جنوب أفريقيا", flag: "🇿🇦", color: "#22c55e", capital: "بريتوريا", desc: "قوة إقليمية ضخمة بموارد معدنية وتصنيعية." },
  SSD: { name: "جنوب السودان", flag: "🇸🇸", color: "#1e293b", capital: "جوبا", desc: "دولة ناشئة مليئة بالموارد النفطية." },
  DJI: { name: "جيبوتي", flag: "🇩🇯", color: "#3b82f6", capital: "جيبوتي", desc: "نقطة ارتكاز للقواعد العسكرية العالمية." },
  COM: { name: "جزر القمر", flag: "🇰🇲", color: "#16a34a", capital: "موروني", desc: "تجمع جزر استراتيجي بمضيق موزمبيق." },
  GNQ: { name: "غينيا الاستوائية", flag: "🇬🇶", color: "#16a34a", capital: "مالابو", desc: "منتج طاقة قوي بغرب القارة الإفريقية." },
  RWA: { name: "رواندا", flag: "🇷🇼", color: "#2563eb", capital: "كيغالي", desc: "نمر أفريقي صاعد وتكنولوجيا واعدة." },
  ZMB: { name: "زامبيا", flag: "🇿🇲", color: "#16a34a", capital: "لوساكا", desc: "مركز رائد لإنتاج النحاس وتصديره." },
  ZWE: { name: "زيمبابوي", flag: "🇿🇼", color: "#22c55e", capital: "هراري", desc: "عمق زراعي وموارد معدنية غنية." },
  CPV: { name: "الرأس الأخضر", flag: "🇨🇻", color: "#0ea5e9", capital: "برايا", desc: "خط الملاحة التاريخي في عرض المحيط." },
  SEN: { name: "السنغال", flag: "🇸🇳", color: "#22c55e", capital: "داكار", desc: "منارة غرب أفريقيا الحضارية والاستراتيجية." },
  SDN: { name: "السودان", flag: "🇸🇩", color: "#dc2626", capital: "الخرطوم", desc: "سلة غذاء واحة متقاطعة الأطراف." },
  SLE: { name: "سيراليون", flag: "🇸🇱", color: "#10b981", capital: "فريتاون", desc: "موئل للمعادن الثمينة وسواحل حيوية." },
  SYC: { name: "سيشل", flag: "🇸🇨", color: "#0ea5e9", capital: "فيكتوريا", desc: "قوة بحرية سياحية تتوسط المحيط." },
  STP: { name: "ساو تومي وبرينسيب", flag: "🇸🇹", color: "#16a34a", capital: "ساو تومي", desc: "نقطة ارتكاز وحيوية بحرية بخليج غينيا." },
  SWZ: { name: "إسواتيني", flag: "🇸🇿", color: "#1e3a8a", capital: "مبابان", desc: "مملكة صغيرة غنية بالثقافات في الجنوب." },
  SOM: { name: "الصومال", flag: "🇸🇴", color: "#3b82f6", capital: "مقدشيو", desc: "صاحب أطول ساحل وبوابة القرن الأفريقي." },
  GAB: { name: "الغابون", flag: "🇬🇦", color: "#16a34a", capital: "ليبرفيل", desc: "قطاع بترولي غني بالمساحات الخضراء." },
  GMB: { name: "غامبيا", flag: "🇬🇲", color: "#dc2626", capital: "بانجول", desc: "بوابة عبور نهرية غرب القارة." },
  GHA: { name: "غانا", flag: "🇬🇭", color: "#eab308", capital: "أكرا", desc: "مركز تصديري لمناجم الذهب والكاكاو." },
  GIN: { name: "غينيا", flag: "🇬🇳", color: "#ef4444", capital: "كوناكري", desc: "دولة ثروات تعدينية واستراتيجية كبرى." },
  GNB: { name: "غينيا بيساو", flag: "🇬🇼", color: "#ef4444", capital: "بيساو", desc: "منفذ أطلسي حيوي لغرب القارة." },
  KEN: { name: "كينيا", flag: "🇰🇪", color: "#16a34a", capital: "نيروبي", desc: "قلب شرق أفريقيا الاقتصادي واللوجستي." },
  CMR: { name: "الكاميرون", flag: "🇨🇲", color: "#16a34a", capital: "ياوندي", desc: "أفريقيا المصغرة وبوتقة متنوعة." },
  COD: { name: "الكونغو الديمقراطية", flag: "🇨🇩", color: "#3b82f6", capital: "كينشاسا", desc: "كنز المعادن المجهرية والأراضي العملاقة." },
  COG: { name: "الكونغو", flag: "🇨🇬", color: "#22c55e", capital: "برازافيل", desc: "دولة استوائية ونفطية داعمة." },
  CIV: { name: "كوت ديفوار", flag: "🇨🇮", color: "#f97316", capital: "ياموسوكرو", desc: "المركز الاقتصادي الحيوي للغرب." },
  LBY: { name: "ليبيا", flag: "🇱🇾", color: "#16a34a", capital: "طرابلس", desc: "احتياطيات طاقة ضخمة وساحل طويل." },
  LBR: { name: "ليبريا", flag: "🇱🇷", color: "#dc2626", capital: "مونروفيا", desc: "دولة أسسها أحرار بسواحل تجارية." },
  LSO: { name: "ليسوتو", flag: "🇱🇸", color: "#1e3a8a", capital: "ماسيرو", desc: "مملكة جبلية محاصرة بالكامل حليفاً." },
  MAR: { name: "المغرب", flag: "🇲🇦", color: "#dc2626", capital: "الرباط", desc: "حارسة مضيق جبل طارق وقوة وازنة." },
  MRT: { name: "موريتانيا", flag: "🇲🇷", color: "#16a34a", capital: "نواكشوط", desc: "همزة وصل جيوسياسية ومناجم حديد ضخمة." },
  MLI: { name: "مالي", flag: "🇲🇱", color: "#22c55e", capital: "باماكو", desc: "تراث قاري وحاضنة ذهب كبيرة." },
  MDG: { name: "مدغشقر", flag: "🇲🇬", color: "#ef4444", capital: "أنتاناناريفو", desc: "الجزيرة القارة والتنوع البيئي الشامل." },
  MWI: { name: "ملاوي", flag: "🇲🇼", color: "#000000", capital: "ليلونغوي", desc: "القلب الدافئ لأفريقيا بموارد زراعية العظمى." },
  MUS: { name: "موريشيوس", flag: "🇲🇺", color: "#dc2626", capital: "بورت لويس", desc: "جزيرة اقتصادية حرة جاذبة للاستثمار." },
  MOZ: { name: "موزمبيق", flag: "🇲🇿", color: "#16a34a", capital: "مابوتو", desc: "خط الساحل الطويل وتجارة غاز متنامية." },
  NER: { name: "النيجر", flag: "🇳🇪", color: "#f97316", capital: "نيامي", desc: "قاعدة أساسية لمناجم اليورانيوم والصحراء." },
  NGA: { name: "نيجيريا", flag: "🇳🇬", color: "#16a34a", capital: "أبوجا", desc: "أكبر قوة سكانية واقتصادية بأفريقيا." },
  NAM: { name: "ناميبيا", flag: "🇳🇦", color: "#1e3a8a", capital: "ويندهوك", desc: "ثراء الألماس واليورانيوم والمعادن الثمينة." },

  // Europe
  ALB: { name: "ألبانيا", flag: "🇦🇱", color: "#dc2626", capital: "تيرانا", desc: "موقع استراتيجي بالبلقان وإطلالة بحرية." },
  DEU: { name: "ألمانيا", flag: "🇩🇪", color: "#eab308", capital: "برلين", desc: "محرك الصناعات الثقيلة وعملاق التصنيع." },
  AND: { name: "أندورا", flag: "🇦🇩", color: "#1e3a8a", capital: "أندورا لا فيلا", desc: "إمارة جبلية ذات ملاذ ضريبي واقتصاد حر." },
  UKR: { name: "أوكرانيا", flag: "🇺🇦", color: "#facc15", capital: "كييف", desc: "ترسانة القمح الزراعية والحقول اللامتناهية." },
  IRL: { name: "أيرلندا", flag: "🇮🇪", color: "#16a34a", capital: "دبلن", desc: "بوابة تقنية ومالية للأطراف الأوروبية." },
  ISL: { name: "أيسلندا", flag: "🇮🇸", color: "#1e40af", capital: "ريكيافيك", desc: "الجزيرة البركانية والطاقة الأرضية الخضراء." },
  ESP: { name: "إسبانيا", flag: "🇪🇸", color: "#dc2626", capital: "مدريد", desc: "بوابة البحر المتوسط والحضارة التجارية." },
  ITA: { name: "إيطاليا", flag: "🇮🇹", color: "#15803d", capital: "روما", desc: "قوة إرث استراتيجية وأسطول متوسطي." },
  EST: { name: "إستونيا", flag: "🇪🇪", color: "#3b82f6", capital: "تالين", desc: "القوة الرقمية والمجتمع التكنولوجي الطليعي." },
  BEL: { name: "بلجيكا", flag: "🇧🇪", color: "#000000", capital: "بروكسل", desc: "مركز قرارات الناتو والاتحاد الأوروبي." },
  BGR: { name: "بلغاريا", flag: "🇧🇬", color: "#15803d", capital: "صوفيا", desc: "همزة وصل بين سلاسل البلقان العريقة." },
  POL: { name: "بولندا", flag: "🇵🇱", color: "#dc2626", capital: "وارسو", desc: "جدار درع قوي وحشود برية مؤثرة." },
  BLR: { name: "بيلاروسيا", flag: "🇧🇾", color: "#ef4444", capital: "مينسك", desc: "صناعات ثقيلة وعمق جيوسياسي حساس." },
  BIH: { name: "البوسنة والهرسك", flag: "🇧🇦", color: "#1e3a8a", capital: "سراييفو", desc: "تراث البلقان وملتقى طرق الحضارات." },
  CZE: { name: "التشيك", flag: "🇨🇿", color: "#3b82f6", capital: "براغ", desc: "قاعدة تكنولوجية وتصنيع حربي مدمج." },
  GEO: { name: "جورجيا", flag: "🇬🇪", color: "#ef4444", capital: "تبليسي", desc: "طريق القوقاز التجاري المنيع." },
  MNE: { name: "الجبل الأسود", flag: "🇲🇪", color: "#dc2626", capital: "بودغوريتسا", desc: "إطلالة أدرياتيكية استراتيجية." },
  DNK: { name: "الدنمارك", flag: "🇩🇰", color: "#dc2626", capital: "كوبنهاغن", desc: "دولة الملاحة والسيطرة البحرية البالتيقية." },
  RUS: { name: "روسيا", flag: "🇷🇺", color: "#dc2626", capital: "موسكو", desc: "أكبر دولة مساحة وتمتلك موارد وترسانة رهيبة." },
  ROU: { name: "رومانيا", flag: "🇷🇴", color: "#1d4ed8", capital: "بوخارست", desc: "ممر كارباتي وبحر أسود نشط." },
  SVK: { name: "سلوفاكيا", flag: "🇸🇰", color: "#1d4ed8", capital: "براتيسلافا", desc: "محطات تجميع صناعي بالغة التطور." },
  SVN: { name: "سلوفينيا", flag: "🇸🇮", color: "#2563eb", capital: "ليوبليانا", desc: "همزة الوصل بين البلقان ومنتصف أوروبا." },
  SWE: { name: "السويد", flag: "🇸🇪", color: "#2563eb", capital: "ستوكهولم", desc: "صناعات متطورة واقتصاد ابتكاري ودرع شمالي." },
  CHE: { name: "سويسرا", flag: "🇨🇭", color: "#dc2626", capital: "برن", desc: "حصن جبال الألب والحياد الاقتصادي المطلق." },
  SMR: { name: "سان مارينو", flag: "🇸🇲", color: "#60a5fa", capital: "سان مارينو", desc: "أقدم جمهورية دستورية جبلية حرة." },
  SRB: { name: "صربيا", flag: "🇷🇸", color: "#dc2626", capital: "بلجراد", desc: "قلب منطقة البلقان الناري." },
  FRA: { name: "فرنسا", flag: "🇫🇷", color: "#1d4ed8", capital: "باريس", desc: "قوة عالمية نووية واسعة النفوذ الدبلوماسي." },
  FIN: { name: "فنلندا", flag: "🇫🇮", color: "#2563eb", capital: "هلسنكي", desc: "تكنولوجيا عميقة وقوة حدودية صارمة." },
  VAT: { name: "الفاتيكان", flag: "🇻🇦", color: "#eab308", capital: "الفاتيكان", desc: "المركز الروحي والسياسي الأصغر مساحة." },
  HRV: { name: "كرواتيا", flag: "🇭🇷", color: "#ef4444", capital: "زغرب", desc: "ساحل البحر الأدرياتيكي الطويل." },
  LVA: { name: "لاتفيا", flag: "🇱🇻", color: "#9f1239", capital: "ريغا", desc: "واجهة بحر البلطيق ومركز الخدمات." },
  LTU: { name: "ليتوانيا", flag: "🇱🇹", color: "#facc15", capital: "فيلنيوس", desc: "دولة لوجستية متطورة بقطاع التكنولوجيا." },
  LUX: { name: "لوكسمبورغ", flag: "🇱🇺", color: "#dc2626", capital: "لوكسمبورغ", desc: "دولة مدمجة للثروة والأنظمة المالية المركزية." },
  LIE: { name: "ليختنشتاين", flag: "🇱🇮", color: "#1d4ed8", capital: "فادوز", desc: "إمارة جبلية وواحة للمؤسسات الاستثمارية." },
  MLT: { name: "مالطا", flag: "🇲🇹", color: "#ef4444", capital: "فاليتا", desc: "عقدة بحرية متوسطية استراتيجية للغاية." },
  HUN: { name: "المجر", flag: "🇭🇺", color: "#16a34a", capital: "بودابست", desc: "مركز التقاطع البري الرئيسي بأوروبا الوسطى." },
  MKD: { name: "مقدونيا الشمالية", flag: "🇲🇰", color: "#dc2626", capital: "سكوبي", desc: "قلب جبال البلقان التاريخي والمحاذي." },
  MDA: { name: "مولدوفا", flag: "🇲🇩", color: "#2563eb", capital: "كيشيناو", desc: "سهول زراعية وبوابة شرقية مرنة." },
  MCO: { name: "موناكو", flag: "🇲🇨", color: "#dc2626", capital: "موناكو", desc: "دولة الرفاه والملاحة والعواصم المالية." },
  NOR: { name: "النرويج", flag: "🇳🇴", color: "#dc2626", capital: "أوسلو", desc: "قوة النفط والغاز في الشمال البارد." },
  AUT: { name: "النمسا", flag: "🇦🇹", color: "#ef4444", capital: "فيينا", desc: "عاصمة الحياد والتقاطعات الجيوسياسية." },
  NLD: { name: "هولندا", flag: "🇳🇱", color: "#f97316", capital: "أمستردام", desc: "مركز لوجستي وتجاري وموانئ عملاقة." },
  GRC: { name: "اليونان", flag: "🇬🇷", color: "#3b82f6", capital: "أثينا", desc: "مهد الحضارة وصاحبة أكبر أساطيل تجارية بحرية." },
  GBR: { name: "المملكة المتحدة", flag: "🇬🇧", color: "#1e3a8a", capital: "لندن", desc: "قوة بحرية ومالية عظمى بنفوذ دولي مستمر." },

  // North and Central America
  ATG: { name: "أنتيغوا وباربودا", flag: "🇦🇬", color: "#ef4444", capital: "سانت جونز", desc: "دولتان جزريتان وسوق للاستثمارات المباشرة." },
  BHS: { name: "الباهاماس", flag: "🇧🇸", color: "#0ea5e9", capital: "ناساو", desc: "مركز مالي وأرخبيل واسع التغطية." },
  BRB: { name: "باربادوس", flag: "🇧🇧", color: "#0284c7", capital: "بريدج تاون", desc: "ملتقى بحري وأيقونة للكاريبي الخلص." },
  BLZ: { name: "بليز", flag: "🇧🇿", color: "#1d4ed8", capital: "بلموبان", desc: "دولة استراتيجية بغابات كثيفة وحضارات متبقية." },
  PAN: { name: "بنما", flag: "🇵🇦", color: "#2563eb", capital: "بنما", desc: "الحارس الجيوسياسي لأهم قناة بحرية في العالم." },
  JAM: { name: "جامايكا", flag: "🇯🇲", color: "#eab308", capital: "كينغستون", desc: "نفوذ ثقافي ومحطة ملاحية هامة." },
  DMA: { name: "دومينيكا", flag: "🇩🇲", color: "#16a34a", capital: "روسو", desc: "جزيرة الطبيعة والاقتصاد السيادي المرن." },
  DOM: { name: "الدومينيكان", flag: "🇩🇴", color: "#dc2626", capital: "سانتو دومينغو", desc: "الدولة المهيمنة جغرافيا في المنطقة الكاريبية." },
  SLV: { name: "السلفادور", flag: "🇸🇻", color: "#2563eb", capital: "سان سلفادور", desc: "دولة مالية صاعدة وممر استراتيجي للمحيط." },
  KNA: { name: "سانت كيتس", flag: "🇰🇳", color: "#16a34a", capital: "باسيتير", desc: "دولة جزرية مستقرة استثمارياً واقتصادياً." },
  LCA: { name: "سانت لوسيا", flag: "🇱🇨", color: "#3b82f6", capital: "كاستريس", desc: "نقطة اقتصادية لؤلؤية وموقع محصن كاريبي." },
  VCT: { name: "سانت فينسنت", flag: "🇻🇨", color: "#3b82f6", capital: "كينغستاون", desc: "تجمع جزر واسع للاختباء والملاحة." },
  GTM: { name: "غواتيمالا", flag: "🇬🇹", color: "#0ea5e9", capital: "غواتيمالا", desc: "تاريخ عريق ومزيج ديمغرافي حيوي كثيف." },
  GRD: { name: "غرينادا", flag: "🇬🇩", color: "#dc2626", capital: "سانت جورجز", desc: "جزيرة التوابل السريعة الحركة والاتصال." },
  CAN: { name: "كندا", flag: "🇨🇦", color: "#dc2626", capital: "أوتاوا", desc: "مساحات شاسعة ومقومات طبيعية مائية وخشبية ضخمة." },
  CUB: { name: "كوبا", flag: "🇨🇺", color: "#dc2626", capital: "هافانا", desc: "القلعة المعزولة والمؤثرة في قلب البحر الكاريبي." },
  CRI: { name: "كوستاريكا", flag: "🇨🇷", color: "#1d4ed8", capital: "سان خوسيه", desc: "محمية طبيعية سالمة تخلو من التسلح الدائم." },
  MEX: { name: "المكسيك", flag: "🇲🇽", color: "#16a34a", capital: "نيو مكسيكو", desc: "القوة البشرية والاقتصادية الضخمة الرابطة للأمريكيتين." },
  NIC: { name: "نيكاراغوا", flag: "🇳🇮", color: "#3b82f6", capital: "ماناغوا", desc: "دولة مساحات وتضاريس وقنوات بحرية بديلة." },
  HTI: { name: "هايتي", flag: "🇭🇹", color: "#1d4ed8", capital: "بورت أو برانس", desc: "الجزيرة التي ناضلت للحرية وعقدة تاريخية سياسياً." },
  HND: { name: "هندوراس", flag: "🇭🇳", color: "#3b82f6", capital: "تيغوسيغالبا", desc: "نقطة عبور محورية ببحار مضطربة." },
  USA: { name: "الولايات المتحدة", flag: "🇺🇸", color: "#3b82f6", capital: "واشنطن العاصمة", desc: "قوة صناعية عظمى ذات هيمنة شاملة وتقنية نووية." },

  // South America
  ARG: { name: "الأرجنتين", flag: "🇦🇷", color: "#60a5fa", capital: "بوينس آيرس", desc: "أراضي شاسعة من الثروات والمناوبات الجيوسياسية المتغيرة." },
  URY: { name: "أوروغواي", flag: "🇺🇾", color: "#0ea5e9", capital: "مونتفيدو", desc: "سويسرا أمريكا الجنوبية لاقتصادها واستقرارها." },
  ECU: { name: "الإكوادور", flag: "🇪🇨", color: "#eab308", capital: "كيتو", desc: "مركز الأرض ومصدر الثروات الاستوائية الدسمة." },
  BRA: { name: "البرازيل", flag: "🇧🇷", color: "#22c55e", capital: "برازيليا", desc: "معقل الغابات والسيادة المطلقة لموارد اللاتينية." },
  BOL: { name: "بوليفيا", flag: "🇧🇴", color: "#dc2626", capital: "لاباز", desc: "منصة جبلية مليئة بالمعادن والموارد الكامنة." },
  PER: { name: "بيرو", flag: "🇵🇪", color: "#ef4444", capital: "ليما", desc: "خط أمريكا الغربي وملجأ الحضارات والإرث الدفين." },
  PRY: { name: "باراغواي", flag: "🇵🇾", color: "#dc2626", capital: "أسونسيون", desc: "أراضٍ خصبة حبيسة تصدر طاقة كهربائية ضخمة." },
  CHL: { name: "تشيلي", flag: "🇨🇱", color: "#ef4444", capital: "سانتياغو", desc: "أطول قطاع بحري ومعادن جبال الأنديز الهائلة." },
  SUR: { name: "سورينام", flag: "🇸🇷", color: "#16a34a", capital: "باراماريبو", desc: "قاعدة تجمعات وثروات بيئية وغابات لم تُمس." },
  GUY: { name: "غيانا", flag: "🇬🇾", color: "#22c55e", capital: "جورج تاون", desc: "قوة صاعدة باكتشافات البترول الهائلة والجديدة." },
  VEN: { name: "فنزويلا", flag: "🇻🇪", color: "#facc15", capital: "كاراكاس", desc: "أحد أكبر الاحتياطيات النفطية المخبأة على الأراضي." },
  COL: { name: "كولومبيا", flag: "🇨🇴", color: "#eab308", capital: "بوغوتا", desc: "الملتقى بين الأطلسي والهادي ونقطة الجذب الإقليمية." },

  // Oceania
  AUS: { name: "أستراليا", flag: "🇦🇺", color: "#1e3a8a", capital: "كانبيرا", desc: "قارة معزولة شديدة الدفاع وغنية كلياً بالمعادن." },
  PNG: { name: "بابوا غينيا", flag: "🇵🇬", color: "#dc2626", capital: "بورت مورسبي", desc: "موطن الغابات والجبال الخفية الوعرة والصلبة." },
  PLW: { name: "بالاو", flag: "🇵🇼", color: "#3b82f6", capital: "نغرولمود", desc: "قواعد جزرية متقدمة للمراقبة الغربية." },
  TON: { name: "تونغا", flag: "🇹🇴", color: "#dc2626", capital: "نوكو ألوفا", desc: "المملكة البولينيزية الصارمة الصامدة." },
  TUV: { name: "توفالو", flag: "🇹🇻", color: "#60a5fa", capital: "فونافوتي", desc: "دولة جزرية محاصرة بالتيارات وتحظى باهتمام رقمي." },
  WSM: { name: "ساموا", flag: "🇼🇸", color: "#dc2626", capital: "أبيا", desc: "نقطة ارتكاز إرثية وقانونية لوسط المحيط الهادئ." },
  SLB: { name: "جزر سليمان", flag: "🇸🇧", color: "#1d4ed8", capital: "هونيارا", desc: "أرخبيل استوائي بالغ التعقيد والتوزيع." },
  FJI: { name: "فيجي", flag: "🇫🇯", color: "#60a5fa", capital: "سوفا", desc: "مركز حيوي لللوجستيات السياحية والعسكرية أحياناً." },
  VUT: { name: "فانواتو", flag: "🇻🇺", color: "#dc2626", capital: "بورت فيلا", desc: "ديمقراطيات جزرية وملجأ بعيد للمنصات الاقتصادية." },
  FSM: { name: "ميكرونيسيا", flag: "🇫🇲", color: "#60a5fa", capital: "باليكير", desc: "تجمع جزر فاحص لمسار الأمواج التجارية والبيئية." },
  KIR: { name: "كيريباتي", flag: "🇰🇮", color: "#ef4444", capital: "تاراوا", desc: "أكبر مسار أرخبيلي عرضي مقسم على خط التاريخ." },
  MHL: { name: "مارشال", flag: "🇲🇭", color: "#1d4ed8", capital: "ماجورو", desc: "محطة قواعد وقواعد بحثية للمياه المفتوحة." },
  NRU: { name: "ناورو", flag: "🇳🇷", color: "#1e3a8a", capital: "يارين", desc: "صغيرة المساحة ولكن بتاريخ عميق ومحطات تمويل." },
  NZL: { name: "نيوزيلندا", flag: "🇳🇿", color: "#1e3a8a", capital: "ويلينغتون", desc: "نقطة ارتكاز أمنية وعميقة التحالف بالهادي." },

  // Extra / Remaining Territories
  PRT: { name: "البرتغال", flag: "🇵🇹", color: "#15803d", capital: "لشبونة", desc: "دولة تاريخية عريقة على المحيط الأطلسي." },
  NPL: { name: "نيبال", flag: "🇳🇵", color: "#1d4ed8", capital: "كاتماندو", desc: "موطن قمة إفرست وسلسلة جبال الهيمالايا." },
  TWN: { name: "تايوان", flag: "🇹🇼", color: "#2563eb", capital: "تايبيه", desc: "مركز عالمي بارز لإنتاج الرقائق وأشباه الموصلات." },
  GRL: { name: "جرينلاند", flag: "🇬🇱", color: "#dfebd6", capital: "نوك", desc: "أكبر جزيرة في العالم تغطيها الثلوج." },
  ISR: { name: "فلسطين المحتلة", flag: "🇵🇸", color: "#2563eb", capital: "القدس", desc: "أرض مقدسة ذات تاريخ عريق وموقع استراتيجي بالشرق الأوسط." },
  SOL: { name: "أرض الصومال", flag: "🇸🇴", color: "#16a34a", capital: "هرجيسا", desc: "جمهورية معلنة ذاتياً في القرن الإفريقي." },
  XKX: { name: "كوسوفو", flag: "🇽🇰", color: "#1e3a8a", capital: "بريشتينا", desc: "دولة فتية في شبه جزيرة البلقان." },
  ESH: { name: "الصحراء الغربية", flag: "🇪🇭", color: "#dc2626", capital: "العيون", desc: "منطقة غنية بالفوسفات والسواحل في شمال غرب إفريقيا." },
  TTO: { name: "ترينيداد وتوباغو", flag: "🇹🇹", color: "#9f1239", capital: "بورت أوف سبين", desc: "دولة ثنائية الجزر غنية بالنفط والغاز في الكاريبي." },
  PRI: { name: "بورتوريكو", flag: "🇵🇷", color: "#2563eb", capital: "سان خوان", desc: "إقليم أمريكي يتمتع بحكم ذاتي في الكاريبي." },
  BMU: { name: "برمودا", flag: "🇧🇲", color: "#9f1239", capital: "هاميلتون", desc: "أرخبيل في المحيط الأطلسي يشتهر بالقطاع المالي والسياحي." },
  FLK: { name: "جزر فوكلاند", flag: "🇫🇰", color: "#1e3a8a", capital: "ستانلي", desc: "جزر ذات إدارة بريطانية جنوب المحيط الأطلسي." },
  MAC: { name: "ماكاو", flag: "🇲🇴", color: "#0d9488", capital: "ماكاو", desc: "منطقة إدارية خاصة تابعة للصين تشتهر بالسياحة." },
  DHK: { name: "دكليا", flag: "🇬🇧", color: "#1e3a8a", capital: "إبيسكوبي", desc: "قاعدة عسكرية سيادية بريطانية في قبرص." },
  AKR: { name: "أكروتيري", flag: "🇬🇧", color: "#1e3a8a", capital: "إبيسكوبي", desc: "منطقة قاعدة عسكرية سيادية بريطانية في قبرص." },
  MAF: { name: "سانت مارتن", flag: "🇲🇫", color: "#ef4444", capital: "ماريغوت", desc: "القسم الفرنسي من جزيرة سانت مارتن الكاريبية." },
  SXM: { name: "سينت مارتن", flag: "🇸🇽", color: "#3b82f6", capital: "فيليبسبورج", desc: "القسم الهولندي من جزيرة سانت مارتن الكاريبية." },
  BIS: { name: "الجزيرة البرازيلية", flag: "🇧🇷", color: "#22c55e", capital: "برازيليا", desc: "جزيرة صغيرة متنازع عليها محاطة بنهر الأوروغواي." },
  GIB: { name: "جبل طارق", flag: "🇬🇮", color: "#ef4444", capital: "جبل طارق", desc: "صخرة استراتيجية بريطانية تطل على المضيق." },
  CYN: { name: "جمهورية شمال قبرص", flag: "🇹🇷", color: "#ef4444", capital: "نيقوسيا الشمالية", desc: "دولة معلنة في شمال جزيرة قبرص." },
  CNM: { name: "المنطقة العازلة بقبرص", flag: "🇺🇳", color: "#60a5fa", capital: "نيقوسيا", desc: "منطقة عازلة تحت إدارة الأمم المتحدة في قبرص." },
  SIA: { name: "سياشين", flag: "🇮🇳", color: "#cbd5e1", capital: "دلهي/إسلام أباد", desc: "أعلى جبهة قتال جليدية متنازع عليها في العالم." },
  BAY: { name: "بايكونور", flag: "🇰🇿", color: "#2563eb", capital: "بايكونور", desc: "مدينة وموقع إطلاق فضائي مستأجر لروسيا في كازاخستان." },
  SPI: { name: "باتاغونيا الجنوبية", flag: "🇨🇱", color: "#cbd5e1", capital: "سانتياغو", desc: "حقل جليدي ضخم متنازع عليه في جبال الأنديز الجنوبية." },
  BTA: { name: "بير طويل", flag: "🏳️", color: "#cbd5e1", capital: "لا يوجد", desc: "منطقة غير مطروقة وغير تابعة لأي دولة بين مصر والسودان." },
  NCL: { name: "كاليدونيا الجديدة", flag: "🇳🇨", color: "#3b82f6", capital: "نوميا", desc: "أراضي فرنسية في جنوب غرب المحيط الهادئ حيوية وعريقة." },
  CUW: { name: "كوراساو", flag: "🇨🇼", color: "#1e3a8a", capital: "ويلمستاد", desc: "جزيرة هولندية خلابة تتمتع بحكم ذاتي في الكاريبي." },
  ABW: { name: "أروبا", flag: "🇦🇼", color: "#0ea5e9", capital: "أورانجيستاد", desc: "جزيرة كاريبية هولندية تشتهر بشواطئها الجميلة." },
  TCA: { name: "جزر تركس وكايكوس", flag: "🇹🇨", color: "#1e40af", capital: "كوكبرن تاون", desc: "جزر تابعة للمملكة المتحدة في البحر الكاريبي." },
  SPM: { name: "سان بيير وميكلون", flag: "🇵🇲", color: "#2563eb", capital: "سان بيير", desc: "أرخبيل فرنسي صغير قرب السواحل الكندية." },
  PCN: { name: "جزر بيتكيرن", flag: "🇵🇳", color: "#1e3a8a", capital: "آدمزتاون", desc: "مجموعة جزر بريطانية نائية في المحيط الهادئ." },
  PYF: { name: "بولينيزيا الفرنسية", flag: "🇵🇫", color: "#ef4444", capital: "بابيتي", desc: "مجموعة جزر فرنسية شاسعة في المحيط الهادئ." },
  ATF: { name: "الأراضي الجنوبية الفرنسية", flag: "🇹🇫", color: "#1e3a8a", capital: "بورت-أو-فرانسيه", desc: "جزر بركانية نائية تابعة لفرنسا بالمحيط الهندي جنوباً." },
  UMI: { name: "جزر أمريكا النائية", flag: "🇺🇸", color: "#1e3a8a", capital: "واشنطن", desc: "جزر غير مأهولة تابعة للولايات المتحدة بالمحيط الهادئ." },
  MSR: { name: "مونتسرات", flag: "🇲🇸", color: "#1e40af", capital: "بليموث", desc: "جزيرة جبلية تابعة للملكة المتحدة في البحر الكاريبي." },
  VIR: { name: "جزر العذراء الأمريكية", flag: "🇻🇮", color: "#1e3a8a", capital: "شارلوت أمالي", desc: "أراضي أمريكية جزيرية خلابة بالكاريبي." },
  BLM: { name: "سان بارتليمي", flag: "🇧🇱", color: "#2563eb", capital: "غوستافيا", desc: "جزيرة كاريبية فرنسية راقية وجذابة." },
  AIA: { name: "أنغويلا", flag: "🇦🇮", color: "#2563eb", capital: "ذا فالي", desc: "إقليم بريطاني صغير في البحر الكاريبي." },
  VGB: { name: "جزر العذراء البريطانية", flag: "🇻🇬", color: "#1e3a8a", capital: "رود تاون", desc: "أرخبيل بريطاني شهير يضم جزر الكاريبي الخلابة." },
  CYM: { name: "جزر كايمان", flag: "🇰🇾", color: "#1e3a8a", capital: "جورج تاون", desc: "مركز مالي عالمي وإقليم بريطاني بالكاريبي." },
  HMD: { name: "جزيرة هيرد وجزر ماكدونالد", flag: "🇦🇺", color: "#1e3a8a", capital: "كانبيرا", desc: "جزر بركانية غير مأهولة تابعة لأستراليا جنوب عريض." },
  SHN: { name: "سانت هيلانة", flag: "🇸🇭", color: "#1e3a8a", capital: "جيمس تاون", desc: "جزيرة بريطانية نائية بالمحيط الأطلسي اشتهرت بنفي نابليون." },
  JEY: { name: "جيرزي", flag: "🇯🇪", color: "#ef4444", capital: "سانت هيلير", desc: "جزيرة تابعة للتاج البريطاني تقع بقرب سواحل فرنسا." },
  GGY: { name: "غيرنزي", flag: "🇬🇬", color: "#ef4444", capital: "سانت بيتر بورت", desc: "جزيرة تحت حكم التاج البريطاني بمياه القناة الإنجليزية." },
  IMN: { name: "جزيرة مان", flag: "🇮🇲", color: "#dc2626", capital: "دوغلاس", desc: "جزيرة مستقلة ذاتياً تحت السيادة البريطانية بمياه البحر الأيرلندي." },
  ALA: { name: "جزر أولاند", flag: "🇦🇽", color: "#0ea5e9", capital: "مارييهامن", desc: "أرخبيل يتمتع بحكم ذاتي يتبع لفنلندا ويتحدث السويدية." },
  FRO: { name: "جزر فارو", flag: "🇫🇴", color: "#dc2626", capital: "توشهافن", desc: "أرخبيل يتمتع بحكم ذاتي تابع لمملكة الدنمارك شمال الأطلسي." },
  IOT: { name: "إقليم المحيط الهندي البريطاني", flag: "🇮🇴", color: "#1e3a8a", capital: "دييغو غارسيا", desc: "إقليم بريطاني يضم أرخبيل شاغوس ذو القيمة الاستراتيجية." },
  NFK: { name: "جزيرة نورفولك", flag: "🇳🇫", color: "#16a34a", capital: "كينغستون", desc: "جزيرة صغيرة في المحيط الهادئ تابعة لأستراليا." },
  COK: { name: "جزر كوك", flag: "🇨🇰", color: "#1e3a8a", capital: "آواروا", desc: "جزر تتمتع بارتباط حر مع نيوزيلندا في الهادئ." },
  WLF: { name: "واليس وفوتونا", flag: "🇼🇫", color: "#dc2626", capital: "ماتا-أوتو", desc: "جزر فرنسية نائية في المحيط الهادئ." },
  SGS: { name: "جورجيا الجنوبية وجزر ساندويتش", flag: "🇬🇸", color: "#1e3a8a", capital: "نقطة غريتفيكن", desc: "جزر بريطانية نائية قرب القطب الجنوبي." },
  NIU: { name: "نييوي", flag: "🇳🇺", color: "#eab308", capital: "الوفي", desc: "جزيرة مرجانية صغيرة بارتباط حر مع نيوزيلندا." },
  ASM: { name: "ساموا الأمريكية", flag: "🇦🇸", color: "#1e3a8a", capital: "باغو باغو", desc: "إقليم أمريكي غير مدمج في جنوب المحيط الهادئ." },
  GUM: { name: "غوام", flag: "🇬🇺", color: "#1d4ed8", capital: "هاغاتنيا", desc: "إقليم أمريكي استراتيجي يضم قواعد بحرية وجوية بالهادئ." },
  MNP: { name: "جزر ماريانا الشمالية", flag: "🇲🇵", color: "#1e3a8a", capital: "سايبان", desc: "أراضي تابعة للولايات المتحدة في غرب المحيط الهادئ." },
  CSI: { name: "جزر بحر المرجان", flag: "🇦🇺", color: "#1e3a8a", capital: "كانبيرا", desc: "مجموعة جزر صغيرة غير مأهولة تابعة لأستراليا." },
  SPR: { name: "جزر سبراتلي", flag: "🏳️", color: "#cbd5e1", capital: "لا يوجد", desc: "أرخبيل متنازع عليه بشدة في بحر الصين الجنوبي." },
  CPT: { name: "جزيرة كليبرتون", flag: "🇨🇵", color: "#cbd5e1", capital: "لا يوجد", desc: "جزيرة مرجانية غير مأهولة تابعة لفرنسا شرق المحيط الهادئ." },
  ACI: { name: "جزر أشمور وكارتيير", flag: "🇦🇺", color: "#1e3a8a", capital: "لا يوجد", desc: "جزر خارجية تابعة لأستراليا في المحيط الهندي." },
  BNB: { name: "بانكو باجو نويفو", flag: "🏳️", color: "#cbd5e1", capital: "لا يوجد", desc: "شعب مرجانية صغيرة متنازع عليها في الكاريبي." },
  SCR: { name: "شعب سكاربورو", flag: "🏳️", color: "#cbd5e1", capital: "لا يوجد", desc: "شعب مرجانية متنازع عليها بشدة في بحر الصين الجنوبي." },
  GLP: { name: "جزر غالاباغوس", flag: "🇪🇨", color: "#eab308", capital: "بويرتو باكيريزو مورينو", desc: "جزر غنية بالتنوع البيولوجي الفريد تابعة للإكوادور." },

};

export function getRealisticStartingArmy(iso: string): {
  infantry: number;
  specialForces: number;
  tanks: number;
  artillery: number;
  antiAir: number;
  jets: number;
  reconPlanes: number;
  warships: number;
  submarines: number;
  missiles: number;
} {
  const custom: Record<string, Partial<Record<string, number>>> = {
    CHN: { infantry: 2200, specialForces: 220, tanks: 580, artillery: 310, antiAir: 150, jets: 120, reconPlanes: 40, warships: 35, submarines: 25, missiles: 100 },
    IND: { infantry: 1450, specialForces: 140, tanks: 460, artillery: 400, antiAir: 120, jets: 80, reconPlanes: 30, warships: 15, submarines: 16, missiles: 60 },
    USA: { infantry: 1350, specialForces: 200, tanks: 550, artillery: 250, antiAir: 110, jets: 220, reconPlanes: 60, warships: 40, submarines: 30, missiles: 80 },
    RUS: { infantry: 1300, specialForces: 180, tanks: 650, artillery: 480, antiAir: 140, jets: 150, reconPlanes: 35, warships: 20, submarines: 24, missiles: 150 },
    PRK: { infantry: 1280, specialForces: 100, tanks: 350, artillery: 400, antiAir: 80, jets: 40, reconPlanes: 10, warships: 5, submarines: 15, missiles: 90 },
    PAK: { infantry: 650, specialForces: 60, tanks: 220, artillery: 160, antiAir: 45, jets: 35, reconPlanes: 12, warships: 4, submarines: 5, missiles: 40 },
    IRN: { infantry: 610, specialForces: 50, tanks: 180, artillery: 200, antiAir: 40, jets: 25, reconPlanes: 10, warships: 4, submarines: 3, missiles: 50 },
    KOR: { infantry: 550, specialForces: 55, tanks: 210, artillery: 220, antiAir: 50, jets: 50, reconPlanes: 15, warships: 10, submarines: 12, missiles: 30 },
    VNM: { infantry: 480, specialForces: 40, tanks: 130, artillery: 150, antiAir: 35, jets: 20, reconPlanes: 8, warships: 3, submarines: 4, missiles: 20 },
    EGY: { infantry: 440, specialForces: 45, tanks: 300, artillery: 180, antiAir: 60, jets: 45, reconPlanes: 12, warships: 6, submarines: 4, missiles: 30 },
    TUR: { infantry: 425, specialForces: 50, tanks: 220, artillery: 150, antiAir: 40, jets: 40, reconPlanes: 10, warships: 8, submarines: 6, missiles: 25 },
    SAU: { infantry: 225, specialForces: 30, tanks: 120, artillery: 80, antiAir: 35, jets: 45, reconPlanes: 12, warships: 4, submarines: 0, missiles: 20 },
    ISR: { infantry: 170, specialForces: 40, tanks: 150, artillery: 60, antiAir: 40, jets: 50, reconPlanes: 15, warships: 3, submarines: 3, missiles: 25 },
    DZA: { infantry: 310, specialForces: 25, tanks: 160, artillery: 110, antiAir: 35, jets: 30, reconPlanes: 10, warships: 4, submarines: 3, missiles: 15 },
    MAR: { infantry: 200, specialForces: 20, tanks: 110, artillery: 90, antiAir: 30, jets: 25, reconPlanes: 8, warships: 3, submarines: 0, missiles: 10 },
    UKR: { infantry: 900, specialForces: 80, tanks: 350, artillery: 380, antiAir: 80, jets: 35, reconPlanes: 25, warships: 1, submarines: 0, missiles: 40 },
    BRA: { infantry: 360, specialForces: 30, tanks: 120, artillery: 90, antiAir: 35, jets: 30, reconPlanes: 10, warships: 6, submarines: 5, missiles: 15 },
    GBR: { infantry: 150, specialForces: 35, tanks: 80, artillery: 60, antiAir: 30, jets: 45, reconPlanes: 15, warships: 12, submarines: 8, missiles: 20 },
    FRA: { infantry: 205, specialForces: 35, tanks: 90, artillery: 70, antiAir: 30, jets: 50, reconPlanes: 15, warships: 10, submarines: 8, missiles: 20 },
    DEU: { infantry: 180, specialForces: 25, tanks: 70, artillery: 50, antiAir: 25, jets: 35, reconPlanes: 10, warships: 5, submarines: 4, missiles: 10 },
    JPN: { infantry: 247, specialForces: 30, tanks: 110, artillery: 80, antiAir: 40, jets: 50, reconPlanes: 15, warships: 18, submarines: 14, missiles: 15 },
    IRQ: { infantry: 193, specialForces: 15, tanks: 80, artillery: 60, antiAir: 20, jets: 15, reconPlanes: 5, warships: 1, submarines: 0, missiles: 10 },
    SYR: { infantry: 150, specialForces: 15, tanks: 90, artillery: 80, antiAir: 25, jets: 15, reconPlanes: 5, warships: 1, submarines: 0, missiles: 15 },
    ITA: { infantry: 165, specialForces: 20, tanks: 80, artillery: 55, antiAir: 25, jets: 40, reconPlanes: 10, warships: 8, submarines: 4, missiles: 12 },
    ESP: { infantry: 120, specialForces: 15, tanks: 60, artillery: 45, antiAir: 20, jets: 30, reconPlanes: 8, warships: 6, submarines: 3, missiles: 10 },
    TWN: { infantry: 169, specialForces: 20, tanks: 80, artillery: 70, antiAir: 30, jets: 35, reconPlanes: 10, warships: 4, submarines: 2, missiles: 15 },
    COL: { infantry: 290, specialForces: 15, tanks: 50, artillery: 60, antiAir: 15, jets: 15, reconPlanes: 5, warships: 4, submarines: 3, missiles: 5 },
    SDN: { infantry: 100, specialForces: 10, tanks: 40, artillery: 30, antiAir: 15, jets: 10, reconPlanes: 4, warships: 1, submarines: 0, missiles: 5 },
    YEM: { infantry: 120, specialForces: 8, tanks: 30, artillery: 25, antiAir: 10, jets: 5, reconPlanes: 2, warships: 0, submarines: 0, missiles: 10 },
    JOR: { infantry: 100, specialForces: 15, tanks: 60, artillery: 45, antiAir: 20, jets: 20, reconPlanes: 5, warships: 0, submarines: 0, missiles: 10 },
    KWT: { infantry: 45, specialForces: 8, tanks: 30, artillery: 20, antiAir: 10, jets: 15, reconPlanes: 3, warships: 1, submarines: 0, missiles: 5 },
    ARE: { infantry: 65, specialForces: 12, tanks: 45, artillery: 30, antiAir: 15, jets: 25, reconPlanes: 5, warships: 2, submarines: 0, missiles: 5 },
    QAT: { infantry: 16, specialForces: 4, tanks: 10, artillery: 8, antiAir: 5, jets: 10, reconPlanes: 2, warships: 1, submarines: 0, missiles: 3 },
    OMN: { infantry: 42, specialForces: 6, tanks: 20, artillery: 15, antiAir: 10, jets: 10, reconPlanes: 2, warships: 1, submarines: 0, missiles: 3 },
    LBN: { infantry: 75, specialForces: 5, tanks: 15, artillery: 12, antiAir: 5, jets: 0, reconPlanes: 0, warships: 0, submarines: 0, missiles: 2 }
  };

  const base = {
    infantry: 40,
    specialForces: 4,
    tanks: 8,
    artillery: 10,
    antiAir: 5,
    jets: 2,
    reconPlanes: 1,
    warships: 0,
    submarines: 0,
    missiles: 1
  };

  const c = custom[iso] || {};
  return {
    infantry: c.infantry ?? base.infantry,
    specialForces: c.specialForces ?? base.specialForces,
    tanks: c.tanks ?? base.tanks,
    artillery: c.artillery ?? base.artillery,
    antiAir: c.antiAir ?? base.antiAir,
    jets: c.jets ?? base.jets,
    reconPlanes: c.reconPlanes ?? base.reconPlanes,
    warships: c.warships ?? base.warships,
    submarines: c.submarines ?? base.submarines,
    missiles: c.missiles ?? base.missiles
  };
}
